name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      name: setup
      with:
        go-version: '1.22'
    - uses: actions/checkout@v4
      name: checkout
    - name: test
      run: go test
